upstream api_gateway_php {
    server api-gateway:9000;
}

upstream user_service_php {
    server user-service:9000;
}

upstream order_service_php {
    server order-service:9000;
}

upstream report_service_php {
    server report-service:9000;
}

upstream saga_orchestrator_php {
    server saga-orchestrator:9000;
}

server {
    listen 80;
    server_name _;

    root /var/www/api-gateway/public;
    index index.php;

    client_max_body_size 20m;

    location = /health {
        access_log off;
        return 200 "ok\n";
    }

    location / {
        return 404;
    }

    location ^~ /api {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /var/www/public;
        fastcgi_pass api_gateway_php;
        fastcgi_index index.php;
    }
}

server {
    listen 8081;
    server_name internal-router;

    client_max_body_size 20m;

    location = /health {
        access_log off;
        return 200 "internal-ok\n";
    }

    location ^~ /user {
        rewrite ^/user/?(.*)$ /$1 break;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/public;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param REQUEST_URI $uri$is_args$args;
        fastcgi_pass user_service_php;
    }

    location ^~ /order {
        rewrite ^/order/?(.*)$ /$1 break;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/public;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param REQUEST_URI $uri$is_args$args;
        fastcgi_pass order_service_php;
    }

    location ^~ /report {
        rewrite ^/report/?(.*)$ /$1 break;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/public;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param REQUEST_URI $uri$is_args$args;
        fastcgi_pass report_service_php;
    }

    location ^~ /saga {
        rewrite ^/saga/?(.*)$ /$1 break;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/public;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param REQUEST_URI $uri$is_args$args;
        fastcgi_pass saga_orchestrator_php;
    }
}
